version: '3.7'
services:
  sim:
    build: ./sim
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - HOST_NAME=sim
  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - BASE_URL=http://localhost:3000
      - AUTH0_CLIENT_ID=HqJwHus26P5E7bbbwYqHZ3ghjVc8mYfb
      #- AUTH0_ISSUER_BASE_URL=https://dev-s76bgqu7e5qlmyze.us.auth0.com
      - AUTH0_ISSUER_BASE_URL=http://sim:8080
    depends_on:
      - sim

secrets:
  AUTH0_CLIENT_SECRET:
    file: ./client/.env
    