version: '3.7'
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - BASE_URL=http://localhost:3000
      - AUTH0_CLIENT_ID=HqJwHus26P5E7bbbwYqHZ3ghjVc8mYfb
      - AUTH0_ISSUER_BASE_URL=https://dev-s76bgqu7e5qlmyze.us.auth0.com

secrets:
  AUTH0_CLIENT_SECRET:
    file: ./client/.env
    